apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: private-spider-java-quarkus 
  janus-idp.io/tekton: private-spider-java-quarkus
  backstage.io/kubernetes-id: private-spider-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: private-spider-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  